#Dispaly
screenWidth: 1920
screenHeight: 1080

#My Location
myLat: 0.0
myLon: 0.0
myAlt: 0.0

#Test target Location
tgtLat: 0.0
tgtLon: 0.0
tgtAlt: 0.0

#Settings
defaultMode: false
offlineMode: false